serverAddr = "114.114.114.114"
serverPort = 3699

[[proxies]]
name = "NT"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3000
remotePort = 3000

[[proxies]]
name = "MP"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3005
remotePort = 3005